# Generated by Django 3.1 on 2020-09-15 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usagers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('connect_aidant', "Connexion d'un aidant"), ('activity_check_aidant', "Reprise de connexion d'un aidant"), ('franceconnect_usager', "FranceConnexion d'un usager"), ('update_email_usager', "L'email de l'usager a été modifié"), ('create_attestation', "Création d'une attestation"), ('create_autorisation', "Création d'une autorisation"), ('use_autorisation', "Utilisation d'une autorisation"), ('cancel_autorisation', "Révocation d'une autorisation")], max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('demarche', models.CharField(blank=True, max_length=100, null=True)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('autorisation', models.IntegerField(blank=True, null=True)),
                ('attestation_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('is_remote_mandat', models.BooleanField(default=False)),
                ('aidant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('usager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='usagers.usager')),
            ],
            options={
                'verbose_name': 'entrée de journal',
                'verbose_name_plural': 'entrées de journal',
                'db_table': 'aidants_connect_web_journal',
            },
        ),
    ]
